import {test,expect} from "@playwright/test";
import AxeBuilder from "@axe-core/playwright";
import {signInAsMockFamily,MOCK_A15_ADMIN_ID,MOCK_AVATAR_USER_ID,passParentGate} from "./support/fixtures";
const notices=(page:import("@playwright/test").Page)=>page.getByRole("region",{name:"Thông báo thao tác"});
test("pricing toast waits for success, survives form updates, is deduplicated and dismissible",async({page,context,baseURL})=>{
 await signInAsMockFamily(context,baseURL!,{userId:MOCK_A15_ADMIN_ID});await page.goto('/admin/settings');const panel=page.locator('#ai-pricing');await panel.getByLabel('Provider',{exact:true}).selectOption('fishaudio');await panel.getByLabel('Mã model chính xác').fill('toast-qa-model');await panel.getByLabel('Nguồn giá HTTPS').fill('https://provider.example/pricing');await panel.getByLabel('USD / 1M UTF-8 bytes').fill('15');
 let release!:()=>void;const wait=new Promise<void>(r=>{release=r;});await page.route('**/api/admin/pricing',async r=>{await wait;await r.fulfill({json:{ok:true}});});await panel.getByRole('button',{name:'Lưu đơn giá'}).click();await expect(notices(page).locator('[data-toast-type=success]')).toHaveCount(0);release();await expect(notices(page)).toContainText('Đã lưu đơn giá');
 await panel.getByRole('button',{name:'Lưu đơn giá'}).click();await expect(notices(page).locator('[data-toast-type=success]')).toHaveCount(1);await expect(notices(page).getByRole('status')).toBeVisible();
 const axe=await new AxeBuilder({page}).include('[aria-label="Thông báo thao tác"]').withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();expect(axe.violations).toEqual([]);await notices(page).getByRole('button',{name:'Đóng thông báo'}).focus();await page.waitForTimeout(4700);await expect(notices(page).getByRole('status')).toBeVisible();await notices(page).getByRole('button',{name:'Đóng thông báo'}).click();await expect(notices(page).getByRole('status')).toHaveCount(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
test("pricing failure is an alert, never success, toast hides raw provider diagnostics",async({page,context,baseURL})=>{
 await signInAsMockFamily(context,baseURL!,{userId:MOCK_A15_ADMIN_ID});await page.goto('/admin/settings');const panel=page.locator('#ai-pricing');await panel.getByLabel('Provider',{exact:true}).selectOption('fishaudio');await panel.getByLabel('Mã model chính xác').fill('toast-qa-model');await panel.getByLabel('Nguồn giá HTTPS').fill('https://provider.example/pricing');await panel.getByLabel('USD / 1M UTF-8 bytes').fill('15');await page.route('**/api/admin/pricing',r=>r.fulfill({status:500,json:{error:'PRIVATE_DIAGNOSTIC_SENTINEL'}}));await panel.getByRole('button',{name:'Lưu đơn giá'}).click();await expect(notices(page).getByRole('alert')).toContainText('Chưa lưu được');await expect(notices(page)).not.toContainText('PRIVATE_DIAGNOSTIC_SENTINEL');await expect(notices(page).locator('[data-toast-type=success]')).toHaveCount(0);
});
test("profile zero-row save is a failure toast; actual acknowledgement yields success",async({page,context,baseURL})=>{
 await signInAsMockFamily(context,baseURL!,{userId:MOCK_AVATAR_USER_ID});await page.goto('/');await page.getByRole('button',{name:'Hồ sơ của bé'}).click();await passParentGate(page);await page.getByRole('heading',{name:'Hồ sơ gia đình'}).waitFor();let saved=false;await page.route('**/rest/v1/profiles?*',async r=>{if(r.request().method()==='PATCH')await r.fulfill({json:saved?[{id:MOCK_AVATAR_USER_ID}]:[]});else await r.continue();});await page.getByRole('button',{name:'Lưu',exact:true}).click();await expect(notices(page).getByRole('alert')).toContainText('Chưa lưu được hồ sơ');await expect(notices(page).locator('[data-toast-type=success]')).toHaveCount(0);saved=true;await page.getByRole('button',{name:'Lưu',exact:true}).click();await expect(notices(page).locator('[data-toast-type=success]')).toContainText('Đã lưu hồ sơ');
});
