import { test, expect } from "@playwright/test";
import AxeBuilder from "@axe-core/playwright";
import { signInAsMockFamily, MOCK_A15_ADMIN_ID } from "./support/fixtures";
const mock = "http://127.0.0.1:54321";
test.beforeAll(async () => { const r = await fetch(mock + "/__e2e/secrets-scan", { method: "POST", body: JSON.stringify({ on: true }) }); expect(r.ok).toBe(true); });
test.afterAll(async () => { await fetch(mock + "/__e2e/secrets-scan", { method: "POST", body: JSON.stringify({ on: false }) }); });
test("Fish pricing UI labels million UTF-8 bytes, converts price and keeps zero explicit", async ({ page, context, baseURL }) => {
  await signInAsMockFamily(context, baseURL!, { userId: MOCK_A15_ADMIN_ID });
  await page.goto("/admin/settings");
  const panel = page.locator("#ai-pricing");
  await panel.getByLabel("Provider", { exact: true }).selectOption("fishaudio");
  await expect(panel.getByLabel("Loại", { exact: true })).toHaveValue("tts");
  await expect(panel.getByLabel("Loại", { exact: true })).toBeDisabled();
  await panel.getByLabel("Mã model chính xác").fill("r01-ui-model");
  await panel.getByLabel("Nguồn giá HTTPS").fill("https://provider.example/pricing");
  await panel.getByLabel("USD / 1M UTF-8 bytes").fill("15");
  const sent = page.waitForRequest(r => r.url().endsWith("/api/admin/pricing") && r.method() === "POST");
  await panel.getByRole("button", { name: "Lưu đơn giá" }).click();
  expect((await sent).postDataJSON()).toMatchObject({ unit: 0.000015, billingUnit: "utf8_bytes", kind: "tts" });
  await expect(panel.getByRole("status")).toContainText("Chỉ áp dụng cho lần gọi mới");
  await panel.getByLabel("USD / 1M UTF-8 bytes").fill("0");
  const zero = page.waitForRequest(r => r.url().endsWith("/api/admin/pricing") && r.method() === "POST");
  await panel.getByRole("button", { name: "Lưu đơn giá" }).click();
  expect((await zero).postDataJSON().unit).toBe(0);
  await expect(panel.getByRole("status")).toContainText("Chỉ áp dụng cho lần gọi mới");
  const a = await new AxeBuilder({ page }).include("#ai-pricing").withTags(["wcag2a", "wcag2aa", "wcag21aa"]).analyze();
  expect(a.violations).toEqual([]);
});
test("real hermetic Fish path persists versioned bytes; no confirmed price is unknown, new price estimates only new attempts", async ({ context, baseURL }) => {
  await signInAsMockFamily(context, baseURL!, { userId: MOCK_A15_ADMIN_ID });
  const text = " [whisper] Bé Thỏ, 2 con gấu! 🐻 ";
  const body = { voiceId: "fish:e2efishvoice01", language: "vi", text };
  const first = await context.request.post("/api/voice/tts", { data: body });
  expect(first.status()).toBe(200);
  const model = first.headers()["x-tts-model"];
  expect(model).toBeTruthy();
  const rows = async () => (await context.request.get(mock + "/rest/v1/ai_cost_ledger?user_id=eq." + MOCK_A15_ADMIN_ID + "&provider=eq.fishaudio", { headers: { Authorization: "Bearer e2e-fake-service-role-key" } })).json();
  const before = (await rows()).at(-1);
  expect(before).toMatchObject({ billing_unit: "utf8_bytes", usage_version: 2, units: Buffer.byteLength("Bé Thỏ, 2 con gấu! 🐻", "utf8"), estimated_usd: null, status: "succeeded" });
  const price = await context.request.post("/api/admin/pricing", { data: { provider: "fishaudio", model, kind: "tts", input: null, output: null, unit: 0.000015, billingUnit: "utf8_bytes", source: "https://provider.example/pricing" } });
  expect(price.status()).toBe(200);
  expect((await context.request.post("/api/voice/tts", { data: body })).status()).toBe(200);
  const after = await rows();
  const latest = after.at(-1);
  expect(latest.price_snapshot).toMatchObject({ billing_unit: "utf8_bytes", price_version: 2 });
  expect(latest.estimated_usd).toBeCloseTo(latest.units * 0.000015, 12);
  expect(after.find((r: { id: string }) => r.id === before.id)).toEqual(before);
  const raw = JSON.stringify(after);
  for (const privateValue of ["PLANTED", "e2efishvoice01", "Bé Thỏ"]) expect(raw).not.toContain(privateValue);
});
test("legacy Fish estimates are visibly excluded instead of shown as known zero", async ({ page, context, baseURL }) => {
  await signInAsMockFamily(context, baseURL!, { userId: MOCK_A15_ADMIN_ID });
  await page.route("**/api/admin/measurement?*", r => r.fulfill({ json: { days: 14, since: "2026-10-07", timezone: "UTC", costs: [], totals: { attempts: 1, estimated_usd: null, unknown_cost: 1, pending: 0, byo_attempts: 0, legacy_unit_attempts: 1 }, funnel: { signup: 0, home_view: 0, first_listen: 0, story_created: 0 } } }));
  await page.goto("/admin/analytics");
  const panel = page.getByRole("region", { name: "Đo lường first-party" });
  await expect(panel).toContainText("lượt Fish cũ đếm ký tự");
  await expect(panel).toContainText("Không cộng ước tính cũ vào tổng");
  await expect(panel).toContainText("Chưa xác định");
});
