import { NextRequest } from "next/server";
import { createClient } from "@/lib/supabase/server";
import { requirePermission } from "@/lib/admin-permissions";
import { z } from "zod";
import { optionalText, parseJsonBody, requiredText, uuid } from "@/lib/api-validation";
import { normalizeVoiceLanguage } from "@/lib/voice-selection";
import { VOICE_ID_PATTERN } from "@/lib/provider-keys";

const DefaultVoiceBody = z.object({
  // ElevenLabs voice id, or `fish:<id>` for a Fish Audio voice (A-04b).
  voice_id: requiredText(120).regex(VOICE_ID_PATTERN, "voice_id không hợp lệ"),
  name: requiredText(100),
  language: requiredText(10).regex(/^[a-z]{2,3}(-[a-zA-Z0-9]{2,8})*$/, "Mã ngôn ngữ không hợp lệ"),
  description: optionalText(500),
  preview_url: optionalText(2048).pipe(z.url().optional()),
  gender: optionalText(20),
});


/**
 * GET /api/voice/defaults?language=vi
 * Returns active default voices for a language (or all).
 *
 * POST /api/voice/defaults  (admin only)
 * Body: { voice_id, name, language, description?, preview_url?, gender? }
 *
 * DELETE /api/voice/defaults?id=uuid  (admin only)
 */

export async function GET(request: NextRequest) {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) {
    return Response.json({ error: "Unauthorized" }, { status: 401 });
  }

  const language = request.nextUrl.searchParams.get("language");

  let query = supabase
    .from("default_voices")
    .select("*")
    .eq("is_active", true)
    .order("language")
    .order("sort_order", { ascending: true }).order("id");

  if (language) {
    query = query.eq("language", normalizeVoiceLanguage(language) ?? language);
  }

  const { data, error } = await query;
  if (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }

  return Response.json({ voices: data ?? [] });
}

export async function POST(request: NextRequest) {
  const supabase = await createClient();
  // A-02: permission check shared with RLS (has_permission).
  const denied = await requirePermission(supabase, "voices.manage");
  if (denied) return denied;
  // audit: db-trigger default_voices (A-03 — the write below runs as the caller, trigger logs it)

  const parsed = await parseJsonBody(request, DefaultVoiceBody);
  if (!parsed.ok) return parsed.response;
  const { voice_id, name, description, preview_url, gender } = parsed.data;
  const language=normalizeVoiceLanguage(parsed.data.language) ?? parsed.data.language;

  // Get max sort_order for this language
  const { data: existing } = await supabase
    .from("default_voices")
    .select("sort_order")
    .eq("language", language)
    .order("sort_order", { ascending: false })
    .limit(1);

  const nextOrder = (existing?.[0]?.sort_order ?? -1) + 1;

  const { data, error } = await supabase
    .from("default_voices")
    .upsert(
      {
        voice_id,
        name,
        language,
        description: description || null,
        preview_url: preview_url || null,
        gender: gender || null,
        sort_order: nextOrder,
        is_active: true,
      },
      { onConflict: "voice_id,language" }
    )
    .select()
    .single();

  if (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }

  return Response.json({ voice: data });
}

export async function DELETE(request: NextRequest) {
  const supabase = await createClient();
  // A-02: permission check shared with RLS (has_permission).
  const denied = await requirePermission(supabase, "voices.manage");
  if (denied) return denied;
  // audit: db-trigger default_voices (A-03 — the write below runs as the caller, trigger logs it)

  const id = request.nextUrl.searchParams.get("id");
  if (!id) {
    return Response.json({ error: "id required" }, { status: 400 });
  }

  const { error } = await supabase
    .from("default_voices")
    .delete()
    .eq("id", id);

  if (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }

  return Response.json({ ok: true });
}

const OrderBody=z.object({language:z.enum(["vi","en","ja"]),ids:z.array(uuid).min(1).max(100)});
export async function PATCH(request:NextRequest){
  // audit: db-trigger default_voices
 const supabase=await createClient();const denied=await requirePermission(supabase,"voices.manage");if(denied)return denied;
 const parsed=await parseJsonBody(request,OrderBody);if(!parsed.ok)return parsed.response;
 // Audit is generated by audit_default_voices inside the atomic RPC.
 const {data,error}=await supabase.rpc("reorder_default_voices",{p_language:parsed.data.language,p_ids:parsed.data.ids});
 if(error)return Response.json({error:"Danh sách đã thay đổi hoặc chưa sắp xếp được. Tải lại rồi thử lại."},{status:error.code==="22023"?409:503});
 return Response.json(data??{ok:true});
}
